export const SUCCESS = 'success'
export const INFO = 'info'
export const WARNING = 'warning'
export const ERROR = 'error'
export const DURATION_MESSAGE = 3000

export const ASPIRANT_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_USER_ROUTE = '/registration'
export const DICTIONARIES_ROUTE = '/dictionaries'

export const FETCH_USER_ACTION = 'FETCH_USER_ACTION'
export const REQUEST_USER_ACTION = 'REQUEST_USER_ACTION'
export const FAILURE_USER_ACTION = 'FAILURE_USER_ACTION'

export const SET_MESSAGE_ACTION = 'SET_MESSAGE_ACTION'
export const CLEAR_MESSAGE_ACTION = 'CLEAR_MESSAGE_ACTION'

export const FETCH_DICT_DOC_ACTION = 'FETCH_DICT_DOC_ACTION'
export const REQUEST_DICT_DOC_ACTION = 'REQUEST_DICT_DOC_ACTION'
export const FAILURE_DICT_DOC_ACTION = 'FAILURE_DICT_DOC_ACTION'
export const INS_DICT_DOC_ACTION = 'INS_DICT_DOC_ACTION'
export const DEL_DICT_DOC_ACTION = 'DEL_DICT_DOC_ACTION'
export const UPD_DICT_DOC_ACTION = 'UPD_DICT_DOC_ACTION'

export const FETCH_DICT_COUNTRY_ACTION = 'FETCH_DICT_COUNTRY_ACTION'
export const REQUEST_DICT_COUNTRY_ACTION = 'REQUEST_DICT_COUNTRY_ACTION'
export const FAILURE_DICT_COUNTRY_ACTION = 'FAILURE_DICT_COUNTRY_ACTION'
export const INS_DICT_COUNTRY_ACTION = 'INS_DICT_COUNTRY_ACTION'
export const DEL_DICT_COUNTRY_ACTION = 'DEL_DICT_COUNTRY_ACTION'
export const UPD_DICT_COUNTRY_ACTION = 'UPD_DICT_COUNTRY_ACTION'

export const FETCH_DICT_EDUCATION_LEVELS_ACTION = 'FETCH_DICT_EDUCATION_LEVELS_ACTION'
export const REQUEST_DICT_EDUCATION_LEVELS_ACTION = 'REQUEST_DICT_EDUCATION_LEVELS_ACTION'
export const FAILURE_DICT_EDUCATION_LEVELS_ACTION = 'FAILURE_DICT_EDUCATION_LEVELS_ACTION'
export const INS_DICT_EDUCATION_LEVELS_ACTION = 'INS_DICT_EDUCATION_LEVELS_ACTION'
export const DEL_DICT_EDUCATION_LEVELS_ACTION = 'DEL_DICT_EDUCATION_LEVELS_ACTION'
export const UPD_DICT_EDUCATION_LEVELS_ACTION = 'UPD_DICT_EDUCATION_LEVELS_ACTION'

export const FETCH_DICT_CITY_ACTION = 'FETCH_DICT_CITY_ACTION'
export const REQUEST_DICT_CITY_ACTION = 'REQUEST_DICT_CITY_ACTION'
export const FAILURE_DICT_CITY_ACTION = 'FAILURE_DICT_CITY_ACTION'
export const INS_DICT_CITY_ACTION = 'INS_DICT_CITY_ACTION'
export const DEL_DICT_CITY_ACTION = 'DEL_DICT_CITY_ACTION'
export const UPD_DICT_CITY_ACTION = 'UPD_DICT_CITY_ACTION'


